server:
  port: 8080

spring:
  ### Enable H2 Console Access
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:userdb;NON_KEYWORDS=USER
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update